name: pointer_interceptor_wasm_test
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.6.0-55.0.dev

dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  rexios_lints: ^7.0.0



flutter:

  uses-material-design: true



